with-expecter: true
packages:
    github.com/adnvilla/payment-gateway-go/src/bounded_context/payment_service/application/usecase:
        config:
            with-expecter: true
            all: true      
            dir: "./src/bounded_context/payment_service/application/usecase/mock"
            outpkg: mock
    github.com/adnvilla/payment-gateway-go/src/bounded_context/payment_service/domain/repository:
        config:
            with-expecter: true
            all: true      
            dir: "./src/bounded_context/payment_service/domain/repository/mock"
            outpkg: mock
    github.com/adnvilla/payment-gateway-go/src/bounded_context/payment_service/domain/service:
        config:
            with-expecter: true
            all: true      
            dir: "./src/bounded_context/payment_service/domain/service/mock"
            outpkg: mock