version: "3.5"

services:
  postgresql:
    restart: always
    image: postgres:13.6
    environment:
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: payment
      POSTGRES_DB: payment
    ports:
      - "5432:5432"
