// Code generated by mockery v2.42.2. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/satori/go.uuid"

	vo "github.com/adnvilla/payment-gateway-go/src/bounded_context/payment_service/domain/vo"
)

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// CaptureOrder provides a mock function with given fields: ctx, order
func (_m *MockOrderRepository) CaptureOrder(ctx context.Context, order vo.CaptureOrderDetail) (uuid.UUID, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CaptureOrder")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, vo.CaptureOrderDetail) (uuid.UUID, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, vo.CaptureOrderDetail) uuid.UUID); ok {
		r0 = rf(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, vo.CaptureOrderDetail) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_CaptureOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CaptureOrder'
type MockOrderRepository_CaptureOrder_Call struct {
	*mock.Call
}

// CaptureOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order vo.CaptureOrderDetail
func (_e *MockOrderRepository_Expecter) CaptureOrder(ctx interface{}, order interface{}) *MockOrderRepository_CaptureOrder_Call {
	return &MockOrderRepository_CaptureOrder_Call{Call: _e.mock.On("CaptureOrder", ctx, order)}
}

func (_c *MockOrderRepository_CaptureOrder_Call) Run(run func(ctx context.Context, order vo.CaptureOrderDetail)) *MockOrderRepository_CaptureOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(vo.CaptureOrderDetail))
	})
	return _c
}

func (_c *MockOrderRepository_CaptureOrder_Call) Return(_a0 uuid.UUID, _a1 error) *MockOrderRepository_CaptureOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_CaptureOrder_Call) RunAndReturn(run func(context.Context, vo.CaptureOrderDetail) (uuid.UUID, error)) *MockOrderRepository_CaptureOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: ctx, order
func (_m *MockOrderRepository) CreateOrder(ctx context.Context, order vo.CreateOrderDetail) (uuid.UUID, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, vo.CreateOrderDetail) (uuid.UUID, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, vo.CreateOrderDetail) uuid.UUID); ok {
		r0 = rf(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, vo.CreateOrderDetail) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockOrderRepository_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order vo.CreateOrderDetail
func (_e *MockOrderRepository_Expecter) CreateOrder(ctx interface{}, order interface{}) *MockOrderRepository_CreateOrder_Call {
	return &MockOrderRepository_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, order)}
}

func (_c *MockOrderRepository_CreateOrder_Call) Run(run func(ctx context.Context, order vo.CreateOrderDetail)) *MockOrderRepository_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(vo.CreateOrderDetail))
	})
	return _c
}

func (_c *MockOrderRepository_CreateOrder_Call) Return(_a0 uuid.UUID, _a1 error) *MockOrderRepository_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_CreateOrder_Call) RunAndReturn(run func(context.Context, vo.CreateOrderDetail) (uuid.UUID, error)) *MockOrderRepository_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
