// Code generated by mockery v2.42.3. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	vo "github.com/adnvilla/payment-gateway-go/src/bounded_context/payment_service/domain/vo"
)

// MockOrderService is an autogenerated mock type for the OrderService type
type MockOrderService struct {
	mock.Mock
}

type MockOrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderService) EXPECT() *MockOrderService_Expecter {
	return &MockOrderService_Expecter{mock: &_m.Mock}
}

// CaptureOrder provides a mock function with given fields: ctx, createOrder
func (_m *MockOrderService) CaptureOrder(ctx context.Context, createOrder vo.CaptureOrder) (vo.CaptureOrderDetail, error) {
	ret := _m.Called(ctx, createOrder)

	if len(ret) == 0 {
		panic("no return value specified for CaptureOrder")
	}

	var r0 vo.CaptureOrderDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, vo.CaptureOrder) (vo.CaptureOrderDetail, error)); ok {
		return rf(ctx, createOrder)
	}
	if rf, ok := ret.Get(0).(func(context.Context, vo.CaptureOrder) vo.CaptureOrderDetail); ok {
		r0 = rf(ctx, createOrder)
	} else {
		r0 = ret.Get(0).(vo.CaptureOrderDetail)
	}

	if rf, ok := ret.Get(1).(func(context.Context, vo.CaptureOrder) error); ok {
		r1 = rf(ctx, createOrder)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderService_CaptureOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CaptureOrder'
type MockOrderService_CaptureOrder_Call struct {
	*mock.Call
}

// CaptureOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - createOrder vo.CaptureOrder
func (_e *MockOrderService_Expecter) CaptureOrder(ctx interface{}, createOrder interface{}) *MockOrderService_CaptureOrder_Call {
	return &MockOrderService_CaptureOrder_Call{Call: _e.mock.On("CaptureOrder", ctx, createOrder)}
}

func (_c *MockOrderService_CaptureOrder_Call) Run(run func(ctx context.Context, createOrder vo.CaptureOrder)) *MockOrderService_CaptureOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(vo.CaptureOrder))
	})
	return _c
}

func (_c *MockOrderService_CaptureOrder_Call) Return(_a0 vo.CaptureOrderDetail, _a1 error) *MockOrderService_CaptureOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderService_CaptureOrder_Call) RunAndReturn(run func(context.Context, vo.CaptureOrder) (vo.CaptureOrderDetail, error)) *MockOrderService_CaptureOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: ctx, createOrder
func (_m *MockOrderService) CreateOrder(ctx context.Context, createOrder vo.CreateOrder) (vo.CreateOrderDetail, error) {
	ret := _m.Called(ctx, createOrder)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 vo.CreateOrderDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, vo.CreateOrder) (vo.CreateOrderDetail, error)); ok {
		return rf(ctx, createOrder)
	}
	if rf, ok := ret.Get(0).(func(context.Context, vo.CreateOrder) vo.CreateOrderDetail); ok {
		r0 = rf(ctx, createOrder)
	} else {
		r0 = ret.Get(0).(vo.CreateOrderDetail)
	}

	if rf, ok := ret.Get(1).(func(context.Context, vo.CreateOrder) error); ok {
		r1 = rf(ctx, createOrder)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockOrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - createOrder vo.CreateOrder
func (_e *MockOrderService_Expecter) CreateOrder(ctx interface{}, createOrder interface{}) *MockOrderService_CreateOrder_Call {
	return &MockOrderService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, createOrder)}
}

func (_c *MockOrderService_CreateOrder_Call) Run(run func(ctx context.Context, createOrder vo.CreateOrder)) *MockOrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(vo.CreateOrder))
	})
	return _c
}

func (_c *MockOrderService_CreateOrder_Call) Return(_a0 vo.CreateOrderDetail, _a1 error) *MockOrderService_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderService_CreateOrder_Call) RunAndReturn(run func(context.Context, vo.CreateOrder) (vo.CreateOrderDetail, error)) *MockOrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderService creates a new instance of MockOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderService {
	mock := &MockOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
